import { StudioDocument } from "@/components/studio-document";

export const metadata = { title: "Privacy policy", description: "How Noerong handles website visits, project enquiries, and AI assistant conversations.", alternates: { canonical: "/privacy" } };
export default function PrivacyPage() {
  return <StudioDocument updated="12 September 2026" label="Your information" title="Privacy policy." intro="This policy explains how Rongali Chaitanya, operating Noerong from Bengaluru, India, handles information connected with this website.">
    <h2>What this website handles</h2><p>You can read the portfolio and essays without creating an account. When you contact hello@noerong.com, your email address, message, and any details you choose to include are used to respond, discuss a project, and manage that relationship. Please include only the information needed for your enquiry.</p>
    <h2>The AI assistant</h2><p>When you send a message, your question and recent conversation are sent through Noerong&apos;s hosting services to DeepSeek to generate a response. Use the assistant only for public information about the studio. Do not submit confidential work, passwords, personal records, or payment information.</p><p>Noerong does not store chat transcripts in its application database. The conversation remains in page memory until you refresh, leave the page, or start a new conversation. DeepSeek processes the submitted information under its own applicable policies, which may include retention and processing outside your country. See <a href="https://cdn.deepseek.com/policies/en-US/deepseek-privacy-policy.html">DeepSeek&apos;s privacy policy</a> and <a href="/assistant-privacy">the assistant privacy details</a>.</p>
    <h2>Technical information and local preferences</h2><p>Hosting and infrastructure providers, including Vercel and Cloudflare, process technical connection information such as IP addresses and request details to deliver the site and protect it from abuse. Noerong&apos;s assistant keeps request counters associated with a daily changing hashed network identifier, rather than storing raw IP addresses in those counters. Expired counters are removed during later requests.</p><p>The motion preference is stored in your browser so the site remembers whether you paused the animated covers. You can remove it using your browser&apos;s site-data controls. Noerong does not run its own advertising campaigns or marketing analytics integration on this site. Third-party content is described below.</p>
    <h2>Social profile links</h2><p>The About page uses a locally rendered link to the founder&apos;s LinkedIn profile. It does not load a LinkedIn badge script or embedded profile. If you follow the link, LinkedIn handles your visit under its own <a href="https://www.linkedin.com/legal/privacy-policy">privacy policy</a>.</p><h2>Sharing and retention</h2><p>Information is shared with service providers as needed to operate the website, answer your enquiry, and generate an AI response. Noerong does not sell personal information. Emails and project records may be retained while needed for the relationship, legitimate record keeping, or legal obligations. Infrastructure and AI providers apply their own retention practices; Noerong does not promise that they keep no logs.</p>
    <h2>Your choices and requests</h2><p>You can use the site without the assistant and contact Noerong directly. To ask about access, correction, deletion, withdrawal of consent where applicable, or another privacy concern, email <a href="mailto:hello@noerong.com?subject=Privacy%20request">hello@noerong.com</a>. Describe the request without sending identity documents unless they are needed and specifically requested. Requests will be handled in accordance with applicable law, including any required verification or record-retention obligations.</p>
    <h2>External sites and changes</h2><p>Project demos, marketplaces, and social platforms have their own policies. This policy covers the Noerong studio website, not every linked product. Material changes to this policy will be reflected here with an updated date.</p>
  </StudioDocument>;
}
