import { Link } from "@/components/plain-link";

export function WaysToWork() {
  return <section className="ways-to-work shell" aria-labelledby="ways-title">
    <div className="section-heading"><div><p className="section-kicker">A sensible place to start</p><h2 id="ways-title">Choose the right<br /><em>first step.</em></h2></div><p>Buy a foundation, clarify one workflow, or commission a scoped build. Different needs deserve different commitments.</p></div>
    <div className="offer-grid">
      <article><p className="offer-eyebrow">01 / Build it yourself</p><h3>Source kits & themes</h3><p className="offer-price">From $29 <span>one-time download</span></p><p>For developers and hands-on teams. Get the code or theme, licence, and setup documentation described in the individual listing.</p><ul><li>Review the live demo and product boundaries</li><li>Choose the kit that fits your workflow</li><li>Hosting and implementation are separate</li></ul><Link className="text-link" href="/projects">Explore the products <span aria-hidden="true">↗</span></Link></article>
      <article className="offer-recommended"><p className="offer-eyebrow">02 / Define the next move</p><h3>Workflow clarity sprint</h3><p className="offer-price">$249 <span>fixed scope · 3 business days</span></p><p>For a team unsure what to build next. A focused review of one workflow, with a practical plan you can act on.</p><ul><li>Current-state map and prioritized friction points</li><li>Recommended flow and implementation brief</li><li>One written revision; no production build</li></ul><Link className="text-link" href="/contact#project-brief">Discuss the sprint <span aria-hidden="true">↗</span></Link></article>
      <article><p className="offer-eyebrow">03 / Make it work for you</p><h3>Setup or custom build</h3><p className="offer-price">Scoped quote <span>agreed before work starts</span></p><p>For a business ready to implement. Adapt an existing product or commission a focused system around your needs.</p><ul><li>Written deliverables and acceptance criteria</li><li>Milestones, revisions, and exclusions agreed</li><li>Testing, deployment, and usable handoff</li></ul><Link className="text-link" href="/contact#project-brief">Start a project brief <span aria-hidden="true">↗</span></Link></article>
    </div><p className="offer-footnote">The first sprint handoff is within 3 business days after the brief and required materials are complete. Revision timing is agreed after your consolidated feedback. Implementation, integrations, migration, hosting, and paid services are not included. <a href="https://contra.com/s/LQq2ZQX6-workflow-clarity-sprint-map-simplify-plan" target="_blank" rel="noreferrer">Read the complete sprint scope on Contra ↗</a>. Existing product-specific setup prices remain available in their listings.</p>
  </section>;
}
