import { StudioDocument } from "@/components/studio-document";

export const metadata = { title: "Terms and conditions", description: "Terms for using the Noerong studio website, portfolio, writing, and AI assistant.", alternates: { canonical: "/terms" } };
export default function TermsPage() {
  return <StudioDocument label="Using this website" title="Terms & conditions." intro="These terms apply to the Noerong studio website, operated by Rongali Chaitanya. Paid projects and product purchases are governed by their separate agreements.">
    <h2>Portfolio and project enquiries</h2><p>The website presents studio work, independent writing, and ways to discuss a project. Sending an enquiry does not create a booking or contract. Scope, price, milestones, ownership, support, and delivery dates must be agreed separately in writing.</p>
    <h2>Content and intellectual property</h2><p>Noerong&apos;s original writing, designs, and other original materials are protected by applicable intellectual property law. Third-party images and materials retain their respective ownership and licences. You may link to this site and use material as permitted by law or its stated licence. Please contact Noerong before republishing substantial original content or presenting the work as your own.</p>
    <h2>Demos and external services</h2><p>Portfolio screenshots and demonstrations may use sample data. A demonstration does not promise that every capability is included in a purchase or custom engagement. External websites, marketplaces, and linked products have their own terms, pricing, and privacy practices.</p>
    <h2>AI and editorial material</h2><p>The assistant is an automated guide. It can make mistakes and cannot negotiate, accept work, guarantee results, or make commitments for Noerong. Confirm important details directly. Essays express personal views and interpretations; references are provided for further investigation. Neither the assistant nor the essays replace professional advice where it is required.</p>
    <h2>Responsible use</h2><p>Do not attempt to access private systems, bypass usage limits, interfere with availability, or submit unlawful or harmful content. If you discover a security issue, report it privately to <a href="mailto:hello@noerong.com?subject=Security%20report">hello@noerong.com</a> with enough information to investigate. Avoid accessing other people&apos;s information or disrupting the service.</p>
    <h2>Availability and your rights</h2><p>The website may change, contain errors, or be temporarily unavailable. No uninterrupted operation or particular business outcome is promised. Nothing in these terms excludes rights or obligations that cannot lawfully be excluded. Any paid-service warranties or remedies should be set out in the applicable agreement.</p>
    <h2>Questions and updates</h2><p>For questions about these terms, contact <a href="mailto:hello@noerong.com">hello@noerong.com</a>. Changes will be posted here with an updated date.</p>
  </StudioDocument>;
}
