export type Product = {
  slug: string;
  name: string;
  stage: "Live product" | "Developer foundation" | "Working demo";
  category: string;
  summary: string;
  problem: string;
  image: string;
  motionCover?: string;
  imageAlt: string;
  liveUrl: string;
  contraUrl?: string;
  sourceKitUrl?: string;
  sourceKitPrice?: string;
  sourceKitLabel?: string;
  offerNote?: string;
  purchaseUrl?: string;
  startingPrice?: string;
  repository?: string;
  tags: string[];
};

export const products: Product[] = [
  {
    slug: "margin-and-matter",
    name: "Margin & Matter",
    stage: "Live product",
    category: "Editorial publishing & WordPress",
    summary: "A considered home for independent writing, with an editorial application, protected writing studio, and a separate native WordPress theme edition.",
    problem: "For writers and creative publications that need both a distinctive reading experience and a practical way to publish.",
    image: "/products/margin-and-matter.png",
    motionCover: "/products/motion/margin-and-matter.mp4",
    imageAlt: "Margin & Matter editorial application: journal, photographic stories, and reading experience",
    liveUrl: "https://margin-and-matter-production.up.railway.app/",
    contraUrl: "https://contra.com/s/7AmsAFLW-margin-and-matter-word-press-branding-and-setup",
    sourceKitUrl: "https://contra.com/products/SnewMMM1-margin-and-matter-editorial-word-press-theme",
    sourceKitPrice: "$29",
    sourceKitLabel: "WordPress theme",
    startingPrice: "$129",
    offerNote: "Two separate editions: the live application includes a custom writing studio. The $29 download is a native WordPress block theme, not that application's source code. The $129 WordPress setup includes the theme, so you do not need to buy it twice. Application customization is quoted to scope. Hosting, domains, paid plugins and content migration are not included.",
    tags: ["Editorial design", "React", "TypeScript", "WordPress"],
  },
  {
    slug: "noerong-proposals",
    name: "Noerong Proposals",
    stage: "Live product",
    category: "Proposal and client approval SaaS",
    summary: "A white-label proposal workspace for accurate pricing, secure client links, comments, decisions, and a complete activity record.",
    problem: "For independent teams still managing scope, calculations, approvals, and follow-up across documents, spreadsheets, and email.",
    image: "/products/noerong-proposals.png",
    motionCover: "/products/motion/noerong-proposals.mp4",
    imageAlt: "Noerong Proposals pipeline dashboard and proposal workflow",
    liveUrl: "https://noerong-proposals-sa-ta7h.bolt.host",
    contraUrl: "https://contra.com/s/lqMU2Wvl-noerong-proposals-branded-proposal-workspace-setup",
    sourceKitUrl: "https://contra.com/products/Al07mNLl-noerong-proposals-source-kit",
    sourceKitPrice: "$29",
    startingPrice: "$299",
    offerNote: "The $299 setup includes the source licence, one buyer-owned deployment, brand configuration, database/auth setup, workflow testing and handoff. Delivery starts after complete assets and access. Hosting and provider fees, custom integrations, payments and e-signatures are excluded.",
    tags: ["Bolt", "React", "TypeScript", "Bolt Cloud"],
  },
  {
    slug: "leaddesk-ai",
    name: "LeadDesk AI",
    stage: "Live product",
    category: "AI lead capture",
    summary: "A white-label website assistant that answers approved FAQs and turns high-intent visitors into structured quote requests.",
    problem: "For service businesses losing ready-to-buy visitors after hours.",
    image: "/products/leaddesk-ai.png",
    motionCover: "/products/motion/leaddesk-ai.mp4",
    imageAlt: "LeadDesk AI customer website and embedded assistant",
    liveUrl: "https://leaddesk-ai-production.up.railway.app",
    contraUrl: "https://contra.com/s/UbWOeM2v-lead-desk-ai-faq-chatbot-and-lead-capture-setup",
    sourceKitUrl: "https://contra.com/products/j2KQHEh8-lead-desk-ai-white-label-chatbot-source-kit",
    sourceKitPrice: "$29",
    purchaseUrl: "https://www.upwork.com/services/product/development-it-a-white-label-ai-chatbot-and-lead-capture-system-for-your-website-2093012217047462206",
    startingPrice: "$149",
    offerNote: "The $149 setup includes the source licence, one business, up to 20 approved FAQs, one deployment, one compatible website embed, testing and handoff. Hosting, domains and optional AI usage are paid by you.",
    tags: ["FastAPI", "OpenAI-ready", "SQLite", "Docker"],
  },
  {
    slug: "followdesk",
    name: "FollowDesk",
    stage: "Live product",
    category: "Lead follow-up automation",
    summary: "A white-label follow-up system that moves new enquiries through a focused sales pipeline and toward a booked call.",
    problem: "For service businesses losing good leads because follow-up depends on memory, spreadsheets, and scattered inboxes.",
    image: "/products/followdesk.png",
    motionCover: "/products/motion/followdesk.mp4",
    imageAlt: "FollowDesk lead follow-up and booking dashboard",
    liveUrl: "https://followdesk-production.up.railway.app",
    contraUrl: "https://contra.com/s/sFBmXXU3-follow-desk-lead-follow-up-and-booking-crm-setup",
    sourceKitUrl: "https://contra.com/products/lJMSSAkT-follow-desk-lead-follow-up-crm-source-kit",
    sourceKitPrice: "$29",
    startingPrice: "$199",
    offerNote: "The $199 setup includes the source licence, one business, up to four approved email steps, one verified SMTP sender, booking link, one deployment and handoff. Staff can stop queued follow-ups after a reply or opt-out. Automatic reply detection and inbox/calendar synchronization are separate integrations.",
    tags: ["FastAPI", "Email automation", "Booking", "SQLite"],
  },
  {
    slug: "reviewdesk",
    name: "ReviewDesk",
    stage: "Live product",
    category: "Customer feedback automation",
    summary: "A white-label system that requests honest feedback, automates reminders, and turns permissioned customer stories into an embeddable trust widget.",
    problem: "For local businesses doing excellent work but failing to turn completed jobs into consistent feedback and credible social proof.",
    image: "/products/reviewdesk.png",
    motionCover: "/products/motion/reviewdesk.mp4",
    imageAlt: "ReviewDesk branded customer feedback experience",
    liveUrl: "https://reviewdesk-noerong.vercel.app",
    contraUrl: "https://contra.com/s/E6bAEMgv-review-desk-feedback-and-testimonial-system-setup",
    sourceKitUrl: "https://contra.com/products/TVvI1cOr-review-desk-feedback-and-testimonial-source-kit",
    sourceKitPrice: "$29",
    startingPrice: "$149",
    offerNote: "The $149 setup includes the source licence, one business, a feedback/request sequence, one verified sender, one persistent deployment, one compatible widget embed and handoff. The public demo does not send email or retain submissions. Provider fees are separate.",
    tags: ["FastAPI", "Review requests", "Testimonials", "SQLite"],
  },
  {
    slug: "clientdesk",
    name: "ClientDesk",
    stage: "Live product",
    category: "Client operations",
    summary: "A white-label client portal for onboarding, project progress, deliverables, approvals, and invoice visibility.",
    problem: "For agencies and consultants losing time to scattered updates, files, approval threads, and invoice follow-up.",
    image: "/products/clientdesk.png",
    motionCover: "/products/motion/clientdesk.mp4",
    imageAlt: "ClientDesk branded client portal and studio dashboard",
    liveUrl: "https://clientdesk-production-6c93.up.railway.app",
    contraUrl: "https://contra.com/s/B6A6Fkcc-client-desk-branded-client-portal-setup",
    sourceKitUrl: "https://contra.com/products/5yhDIHNw-client-desk-white-label-client-portal-source-kit",
    sourceKitPrice: "$49",
    startingPrice: "$249",
    offerNote: "The $249 setup includes the source licence, one business, one workflow, up to three initial client workspaces, one persistent deployment and handoff. Deliverables and payments use your external links; file hosting, payment processing and provider synchronization are excluded.",
    tags: ["FastAPI", "Client portals", "Approvals", "SQLite"],
  },
  {
    slug: "growthdesk",
    name: "GrowthDesk",
    stage: "Developer foundation",
    category: "CRM developer foundation",
    summary: "A developer foundation with protected owner access, enquiry capture and lead stages, plus clearly labelled previews of a wider client workflow.",
    problem: "For service businesses running one customer journey across disconnected forms, inboxes, spreadsheets, portals, and reminder tools.",
    image: "/products/growthdesk.png",
    motionCover: "/products/motion/growthdesk.mp4",
    imageAlt: "GrowthDesk command center with revenue pipeline and automation status",
    liveUrl: "https://growthdesk-production-0258.up.railway.app",
    contraUrl: "https://contra.com/s/bQWU7WFR-growth-desk-crm-foundation-setup-for-one-business",
    sourceKitUrl: "https://contra.com/products/RlzR2x7T-growth-desk-white-label-crm-source-kit",
    sourceKitPrice: "$49",
    startingPrice: "$299",
    offerNote: "Developer foundation, version 1.1. The $49 source kit includes protected single-owner lead management. The $299 setup includes the licence, brand configuration, one fresh persistent deployment, enquiry/stage testing and handoff. Inbox delivery, automation execution, project creation, portal approvals, file downloads, payments and review collection require additional development. The public demo is read-only with fictional records.",
    tags: ["React", "TypeScript", "Lead management", "Developer foundation"],
  },
  {
    slug: "sourceroom",
    name: "SourceRoom",
    stage: "Working demo",
    category: "Content operations",
    summary: "A focused workspace that turns one article, transcript, or set of notes into editable drafts for several channels.",
    problem: "For teams repeatedly rebuilding content from the same strong source.",
    image: "/products/source-room.png",
    imageAlt: "SourceRoom content repurposing workspace",
    liveUrl: "https://rongali-commits.github.io/content-repurposing-workspace/",
    repository: "https://github.com/rongali-commits/content-repurposing-workspace",
    tags: ["Editorial workflow", "Local-first", "JavaScript"],
  },
  {
    slug: "proofread",
    name: "Proofread",
    stage: "Working demo",
    category: "Document review",
    summary: "A transparent workbench that checks documents against custom criteria, shows the evidence, and exports a structured result.",
    problem: "For operations teams comparing many documents against the same rules.",
    image: "/products/proofread.png",
    imageAlt: "Proofread document review workbench",
    liveUrl: "https://rongali-commits.github.io/document-review-workbench/",
    repository: "https://github.com/rongali-commits/document-review-workbench",
    tags: ["Evidence shown", "Local processing", "JSON export"],
  },
  {
    slug: "ledgerflow",
    name: "LedgerFlow",
    stage: "Working demo",
    category: "Billing automation",
    summary: "A repeatable workflow that cleans billing data, validates every record, and prepares audit-ready exports.",
    problem: "For teams losing hours to recurring spreadsheet cleanup and reporting.",
    image: "/products/ledgerflow.png",
    imageAlt: "LedgerFlow billing automation dashboard",
    liveUrl: "https://rongali-commits.github.io/invoice-report-automation/",
    repository: "https://github.com/rongali-commits/invoice-report-automation",
    tags: ["Python", "CSV validation", "PDF output"],
  },
  {
    slug: "prospectlab",
    name: "ProspectLab",
    stage: "Working demo",
    category: "Lead intelligence",
    summary: "A lead-data pipeline that collects public business records, removes duplicates, scores fit, and exports clean prospect lists.",
    problem: "For sales teams spending more time cleaning leads than contacting them.",
    image: "/products/prospectlab.png",
    imageAlt: "ProspectLab lead intelligence dashboard",
    liveUrl: "https://rongali-commits.github.io/lead-intelligence-pipeline/",
    repository: "https://github.com/rongali-commits/lead-intelligence-pipeline",
    tags: ["Python", "Data quality", "CSV export"],
  },
];
